name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "5d7712a5-d5b6-442a-a968-b64ee1a9f642"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "e66f0f3bfd9649959de3665e432fa6c9"

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
